### ISSUE TITLE
Kmesh panic after applying a ServiceEntry

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#261]
**What happened**:

Running in ads mode,

After creating a SE with this guide, 
https://istio.io/latest/docs/tasks/traffic-management/egress/egress-control/#access-an-external-http-service

I found that kmesh panicked. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:

**Comment by hzxuzhonghu** [comment]
stack traces
```
time="2024-04-22T07:27:58Z" level=info msg="controller Start successful" subsys=manager
time="2024-04-22T07:27:58Z" level=info msg="dump StartServer successful" subsys=manager
time="2024-04-22T07:27:58Z" level=info msg="start write CNI config\n" subsys="cni installer"
time="2024-04-22T07:27:58Z" level=info msg="kmesh cni use chained\n" subsys="cni installer"
panic: runtime error: index out of range [3] with length 0

goroutine 16 [running]:
encoding/binary.littleEndian.Uint32(...)
	/usr/local/go/src/encoding/binary/binary.go:84
kmesh.net/kmesh/pkg/nets.ConvertIpToUint32({0xc0009bd2d0?, 0x0?})
	/kmesh/pkg/nets/nets.go:34 +0x68
kmesh.net/kmesh/pkg/controller/envoy.newApiSocketAddress(0xc000085aa8?)
	/kmesh/pkg/controller/envoy/ads_loader.go:144 +0xa7
kmesh.net/kmesh/pkg/controller/envoy.newApiClusterLoadAssignment(0xc000d55500)
	/kmesh/pkg/controller/envoy/ads_loader.go:107 +0x28d
kmesh.net/kmesh/pkg/controller/envoy.(*AdsLoader).CreateApiClusterByCds(0xc000852a50, 0x2, 0xc000798a00)
	/kmesh/pkg/controller/envoy/ads_loader.go:71 +0x150
kmesh.net/kmesh/pkg/controller/envoy.(*ServiceEvent).handleCdsResponse(0xc000859320, 0xc0008c4080)
	/kmesh/pkg/controller/envoy/ads_event.go:168 +0x532
kmesh.net/kmesh/pkg/controller/envoy.(*ServiceEvent).processAdsResponse(0xc000859320, 0xc0008c4080)
	/kmesh/pkg/controller/envoy/ads_event.go:126 +0x174
kmesh.net/kmesh/pkg/controller/envoy.(*AdsStream).AdsStreamProcess(0xc00078e6a8)
	/kmesh/pkg/controller/envoy/ads_stream.go:63 +0x7f
kmesh.net/kmesh/pkg/controller.(*XdsClient).clientResponseProcess(0xc0008be370, {0x32569a0, 0xc0008be3c0})
	/kmesh/pkg/controller/client.go:128 +0x125
created by kmesh.net/kmesh/pkg/controller.(*XdsClient).Run in goroutine 1
	/kmesh/pkg/controller/client.go:151 +0xd1

```
