### ISSUE TITLE
Kmesh daemon crashed

### ISSUE THREAD

**Issue by YaoZengzeng** [kmesh-net/kmesh#703]
**What happened**:

I tried to run e2e tests in ipv6 env:

```bash
root@kurator-linux-0002:~/kmesh# pwd
/root/kmesh
root@kurator-linux-0002:~/kmesh# ./test/e2e/run_test.sh --ipv6 
```

But the Kmesh daemon pod in worker node keeps crashing:

```bash
root@kurator-linux-0002:~/kmesh# kubectl get pods -n kmesh-system  -owide  
NAME          READY   STATUS             RESTARTS        AGE   IP                 NODE                          NOMINATED NODE   READINESS GATES
kmesh-r6fmh   0/1     CrashLoopBackOff   6 (3m51s ago)   10m   fd00:10:244:1::4   kmesh-testing-worker          <none>           <none>
kmesh-slzbp   1/1     Running            0               10m   fd00:10:244::6     kmesh-testing-control-plane   <none>           <none>
```

The log of crashing Kmesh daemon pod:

```bash
time="2024-08-08T07:01:51Z" level=warning msg="get workload from ip [253 0 0 16 2 68 0 1 0 0 0 0 0 0 0 1] FAILED" subsys=pkg/auth
time="2024-08-08T07:01:51Z" level=warning msg="Auth denied for connection: [253 0 0 16 2 68 0 1 0 0 0 0 0 0 0 5] because destination workload not found" subsys=pkg/auth
time="2024-08-08T07:01:51Z" level=info msg="Auth denied for connection: {srcIdentity:{trustDomain: namespace: serviceAccount:} dstNetwork: srcIp:[253 0 0 16 2 68 0 1 0 0 0 0 0 0 0 1] dstIp:[253 0 0 16 2 68 0 1 0 0 0 0 0 0 0 5] dstPort:8080}" subsys=pkg/auth
time="2024-08-08T07:01:51Z" level=warning msg="get workload from ip [253 0 0 16 2 68 0 1 0 0 0 0 0 0 0 1] FAILED" subsys=pkg/auth
time="2024-08-08T07:01:51Z" level=warning msg="Auth denied for connection: [253 0 0 16 2 68 0 1 0 0 0 0 0 0 0 6] because destination workload not found" subsys=pkg/auth
time="2024-08-08T07:01:51Z" level=info msg="Auth denied for connection: {srcIdentity:{trustDomain: namespace: serviceAccount:} dstNetwork: srcIp:[253 0 0 16 2 68 0 1 0 0 0 0 0 0 0 1] dstIp:[253 0 0 16 2 68 0 1 0 0 0 0 0 0 0 6] dstPort:3333}" subsys=pkg/auth
time="2024-08-08T07:01:51Z" level=warning msg="get workload from ip [253 0 0 16 2 68 0 1 0 0 0 0 0 0 0 1] FAILED" subsys=pkg/auth
time="2024-08-08T07:01:51Z" level=warning msg="Auth denied for connection: [253 0 0 16 2 68 0 1 0 0 0 0 0 0 0 6] because destination workload not found" subsys=pkg/auth
time="2024-08-08T07:01:51Z" level=info msg="Auth denied for connection: {srcIdentity:{trustDomain: namespace: serviceAccount:} dstNetwork: srcIp:[253 0 0 16 2 68 0 1 0 0 0 0 0 0 0 1] dstIp:[253 0 0 16 2 68 0 1 0 0 0 0 0 0 0 6] dstPort:8080}" subsys=pkg/auth
time="2024-08-08T07:01:51Z" level=warning msg="exceed the max port count,current only support maximum of 10 ports" subsys=workload_controller
time="2024-08-08T07:01:51Z" level=warning msg="exceed the max port count,current only support maximum of 10 ports" subsys=workload_controller
time="2024-08-08T07:01:51Z" level=info msg="reload workload config from last epoch" subsys=workload_controller
time="2024-08-08T07:01:51Z" level=info msg="echo-1-86160/enrolled-to-kmesh-v1-76f577cfc6-n4r9p: enable Kmesh manage" subsys=manage_controller
time="2024-08-08T07:01:51Z" level=info msg="echo-1-86160/enrolled-to-kmesh-v2-785d4f7df4-7xccg: enable Kmesh manage" subsys=manage_controller
time="2024-08-08T07:01:51Z" level=info msg="echo-1-86160/service-with-waypoint-at-service-granularity-v1-5dbf88d97bfc2m8: enable Kmesh manage" subsys=manage_controller
time="2024-08-08T07:01:51Z" level=info msg="echo-1-86160/service-with-waypoint-at-service-granularity-v2-5844948d94blx2f: enable Kmesh manage" subsys=manage_controller
time="2024-08-08T07:01:51Z" level=info msg="add annotation for pod echo-1-86160/enrolled-to-kmesh-v1-76f577cfc6-n4r9p" subsys=manage_controller
time="2024-08-08T07:01:51Z" level=info msg="add annotation for pod echo-1-86160/enrolled-to-kmesh-v2-785d4f7df4-7xccg" subsys=manage_controller
time="2024-08-08T07:01:51Z" level=info msg="add annotation for pod echo-1-86160/service-with-waypoint-at-service-granularity-v1-5dbf88d97bfc2m8" subsys=manage_controller
time="2024-08-08T07:01:51Z" level=info msg="add annotation for pod echo-1-86160/service-with-waypoint-at-service-granularity-v2-5844948d94blx2f" subsys=manage_controller
time="2024-08-08T07:01:51Z" level=warning msg="exceed the max port count,current only support maximum of 10 ports" subsys=workload_controller
time="2024-08-08T07:01:51Z" level=warning msg="exceed the max port count,current only support maximum of 10 ports" subsys=workload_controller
time="2024-08-08T07:01:51Z" level=info msg="Copied /usr/bin/kmesh-cni to /opt/cni/bin." subsys="cni installer"
time="2024-08-08T07:01:51Z" level=info msg="cni config file: /etc/cni/net.d/10-kindnet.conflist" subsys="cni installer"
time="2024-08-08T07:01:51Z" level=info msg="kmesh-cni was installed but not cleaned up, but we would overwrite it" subsys="cni installer"
time="2024-08-08T07:01:51Z" level=info msg="command Start cni successful" subsys=manager
time="2024-08-08T07:01:52Z" level=warning msg="get workload from ip [253 0 0 16 2 68 0 1 0 0 0 0 0 0 0 1] FAILED" subsys=pkg/telemetry
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100 pc=0x555ea1568c0f]

goroutine 16 [running]:
kmesh.net/kmesh/pkg/controller/telemetry.buildWorkloadMetric(_, _)
        /kmesh/pkg/controller/telemetry/metric.go:323 +0x16f
kmesh.net/kmesh/pkg/controller/telemetry.(*MetricController).buildWorkloadMetric(_, _)
        /kmesh/pkg/controller/telemetry/metric.go:268 +0x285
kmesh.net/kmesh/pkg/controller/telemetry.(*MetricController).Run(0xc00071cc60, {0x555ea2c1f5e0, 0xc000687e00}, 0xc0006aacd0?)
        /kmesh/pkg/controller/telemetry/metric.go:199 +0x545
created by kmesh.net/kmesh/pkg/controller/workload.(*Controller).Run in goroutine 1
        /kmesh/pkg/controller/workload/workload_controller.go:58 +0x14d
kmesh exit
```

**What you expected to happen**:

All components are functioning properly

**How to reproduce it (as minimally and precisely as possible)**:

As above.

**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:

**Comment by YaoZengzeng** [comment]
The ipv4 env was finally able to restart, but it still took several restart.

```bash
root@kurator-linux-0002:~/kmesh# kubectl  get pods -n kmesh-system  -owide 
NAME          READY   STATUS    RESTARTS        AGE     IP            NODE                          NOMINATED NODE   READINESS GATES
kmesh-qjkjw   1/1     Running   0               4m51s   10.244.0.7    kmesh-testing-control-plane   <none>           <none>
kmesh-xcv5g   1/1     Running   3 (4m33s ago)   4m52s   10.244.1.13   kmesh-testing-worker          <none>           <none>
```
