### ISSUE TITLE
Panic with istio 1.24-alpha.96593644e05baa5c1b6aaab3647b2d9335a23942

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#815]
```
k get pod   -n kmesh-system 
NAME          READY   STATUS             RESTARTS      AGE
kmesh-5dcnv   0/1     CrashLoopBackOff   3 (24s ago)   2m28s
```

time="2024-09-05T04:20:28Z" level=warning msg="exceed the max port count,current only support maximum of 10 ports" subsys=workload_controller
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x556bffcab31f]

goroutine 101 [running]:
kmesh.net/kmesh/pkg/controller/workload.(*Processor).handleService(0xc0000c91a0, 0xc000c08210)
	/kmesh/pkg/controller/workload/workload_processor.go:506 +0xdf
kmesh.net/kmesh/pkg/controller/workload.(*Processor).handleAddressTypeResponse(0xc0000c91a0, 0xc0001124d0)
	/kmesh/pkg/controller/workload/workload_processor.go:573 +0x4d2

image 

```
      image: ghcr.io/kmesh-net/kmesh:latest
      imageID: ghcr.io/kmesh-net/kmesh@sha256:9ec2befa7f60f336a5c667ab35234a8d061af92b20ff3edd65e67be3e63613b1

```

**Comment by hzxuzhonghu** [comment]
IN addition to test: i deployed the latest istio version 1.24-alpha.96593644e05baa5c1b6aaab3647b2d9335a23942

**Comment by hzxuzhonghu** [comment]
something might change generating `workload`

**Comment by hzxuzhonghu** [comment]
The services dumped from ztunnel, which can help dignose which service caused panic

```
./istioctl ztunnel-config service ztunnel-bw76z    -n istio-system -ojson
[
    {
        "name": "enrolled",
        "namespace": "another-2-72003",
        "hostname": "enrolled.another-2-72003.svc.cluster.local",
        "vips": [
            "/10.96.209.88"
        ],
        "ports": {
            "443": 18443,
            "7070": 17070,
            "7071": 17071,
            "80": 18080,
            "81": 18081,
            "82": 18082,
            "84": 18084,
            "85": 18085,
            "86": 18086,
            "9090": 19090,
            "9091": 16060,
            "9092": 19091,
            "9093": 16061,
            "9443": 19443
        },
        "endpoints": {
            "Kubernetes//Pod/another-2-72003/enrolled-v1-56b4bc8cb4-nlhfh": {
                "workloadUid": "Kubernetes//Pod/another-2-72003/enrolled-v1-56b4bc8cb4-nlhfh",
                "service": "",
                "port": {
                    "443": 18443,
                    "7070": 17070,
                    "7071": 17071,
                    "80": 18080,
                    "81": 18081,
                    "82": 18082,
                    "84": 18084,
                    "85": 18085,
                    "86": 18086,
                    "9090": 19090,
                    "9091": 16060,
                    "9092": 19091,
                    "9093": 16061,
                    "9443": 19443
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "unenrolled",
        "namespace": "another-2-72003",
        "hostname": "unenrolled.another-2-72003.svc.cluster.local",
        "vips": [
            "/10.96.167.28"
        ],
        "ports": {
            "443": 18443,
            "7070": 17070,
            "7071": 17071,
            "80": 18080,
            "81": 18081,
            "82": 18082,
            "84": 18084,
            "85": 18085,
            "86": 18086,
            "9090": 19090,
            "9091": 16060,
            "9092": 19091,
            "9093": 16061,
            "9443": 19443
        },
        "endpoints": {
            "Kubernetes//Pod/another-2-72003/unenrolled-v1-764b8c8bc5-x2f7g": {
                "workloadUid": "Kubernetes//Pod/another-2-72003/unenrolled-v1-764b8c8bc5-x2f7g",
                "service": "",
                "port": {
                    "443": 18443,
                    "7070": 17070,
                    "7071": 17071,
                    "80": 18080,
                    "81": 18081,
                    "82": 18082,
                    "84": 18084,
                    "85": 18085,
                    "86": 18086,
                    "9090": 19090,
                    "9091": 16060,
                    "9092": 19091,
                    "9093": 16061,
                    "9443": 19443
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "httpbin",
        "namespace": "default",
        "hostname": "httpbin.default.svc.cluster.local",
        "vips": [
            "/10.96.152.80"
        ],
        "ports": {
            "8000": 80
        },
        "endpoints": {
            "Kubernetes//Pod/default/httpbin-65975d4c6f-vr2bx": {
                "workloadUid": "Kubernetes//Pod/default/httpbin-65975d4c6f-vr2bx",
                "service": "",
                "port": {
                    "8000": 80
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "kubernetes",
        "namespace": "default",
        "hostname": "kubernetes.default.svc.cluster.local",
        "vips": [
            "/10.96.0.1"
        ],
        "ports": {
            "443": 6443
        },
        "endpoints": {
            "Kubernetes/discovery.k8s.io/EndpointSlice/default/kubernetes/172.18.0.2": {
                "workloadUid": "Kubernetes/discovery.k8s.io/EndpointSlice/default/kubernetes/172.18.0.2",
                "service": "",
                "port": {
                    "443": 6443
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "sleep",
        "namespace": "default",
        "hostname": "sleep.default.svc.cluster.local",
        "vips": [
            "/10.96.107.149"
        ],
        "ports": {
            "80": 80
        },
        "endpoints": {
            "Kubernetes//Pod/default/sleep-7656cf8794-8jkh4": {
                "workloadUid": "Kubernetes//Pod/default/sleep-7656cf8794-8jkh4",
                "service": "",
                "port": {
                    "80": 80
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "tcp-echo",
        "namespace": "default",
        "hostname": "tcp-echo.default.svc.cluster.local",
        "vips": [
            "/10.96.72.3"
        ],
        "ports": {
            "9000": 9000,
            "9001": 9001
        },
        "endpoints": {
            "Kubernetes//Pod/default/tcp-echo-56fb5bcd86-jgzhz": {
                "workloadUid": "Kubernetes//Pod/default/tcp-echo-56fb5bcd86-jgzhz",
                "service": "",
                "port": {
                    "9000": 9000,
                    "9001": 9001
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "enrolled-to-kmesh",
        "namespace": "echo-1-20882",
        "hostname": "enrolled-to-kmesh.echo-1-20882.svc.cluster.local",
        "vips": [
            "/10.96.153.183"
        ],
        "ports": {
            "443": 18443,
            "7070": 17070,
            "7071": 17071,
            "80": 18080,
            "81": 18081,
            "82": 18082,
            "84": 18084,
            "85": 18085,
            "86": 18086,
            "9090": 19090,
            "9091": 16060,
            "9092": 19091,
            "9093": 16061,
            "9443": 19443
        },
        "endpoints": {
            "Kubernetes//Pod/echo-1-20882/enrolled-to-kmesh-v1-6bcff54977-xqkf2": {
                "workloadUid": "Kubernetes//Pod/echo-1-20882/enrolled-to-kmesh-v1-6bcff54977-xqkf2",
                "service": "",
                "port": {
                    "443": 18443,
                    "7070": 17070,
                    "7071": 17071,
                    "80": 18080,
                    "81": 18081,
                    "82": 18082,
                    "84": 18084,
                    "85": 18085,
                    "86": 18086,
                    "9090": 19090,
                    "9091": 16060,
                    "9092": 19091,
                    "9093": 16061,
                    "9443": 19443
                }
            },
            "Kubernetes//Pod/echo-1-20882/enrolled-to-kmesh-v2-6bf754956c-9djf9": {
                "workloadUid": "Kubernetes//Pod/echo-1-20882/enrolled-to-kmesh-v2-6bf754956c-9djf9",
                "service": "",
                "port": {
                    "443": 18443,
                    "7070": 17070,
                    "7071": 17071,
                    "80": 18080,
                    "81": 18081,
                    "82": 18082,
                    "84": 18084,
                    "85": 18085,
                    "86": 18086,
                    "9090": 19090,
                    "9091": 16060,
                    "9092": 19091,
                    "9093": 16061,
                    "9443": 19443
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "service-with-waypoint-at-service-granularity",
        "namespace": "echo-1-20882",
        "hostname": "service-with-waypoint-at-service-granularity.echo-1-20882.svc.cluster.local",
        "vips": [
            "/10.96.132.36"
        ],
        "ports": {
            "443": 18443,
            "7070": 17070,
            "7071": 17071,
            "80": 18080,
            "81": 18081,
            "82": 18082,
            "84": 18084,
            "85": 18085,
            "86": 18086,
            "9090": 19090,
            "9091": 16060,
            "9092": 19091,
            "9093": 16061,
            "9443": 19443
        },
        "endpoints": {
            "Kubernetes//Pod/echo-1-20882/service-with-waypoint-at-service-granularity-v1-67c47775b5jcl88": {
                "workloadUid": "Kubernetes//Pod/echo-1-20882/service-with-waypoint-at-service-granularity-v1-67c47775b5jcl88",
                "service": "",
                "port": {
                    "443": 18443,
                    "7070": 17070,
                    "7071": 17071,
                    "80": 18080,
                    "81": 18081,
                    "82": 18082,
                    "84": 18084,
                    "85": 18085,
                    "86": 18086,
                    "9090": 19090,
                    "9091": 16060,
                    "9092": 19091,
                    "9093": 16061,
                    "9443": 19443
                }
            },
            "Kubernetes//Pod/echo-1-20882/service-with-waypoint-at-service-granularity-v2-5575b76f95jjh89": {
                "workloadUid": "Kubernetes//Pod/echo-1-20882/service-with-waypoint-at-service-granularity-v2-5575b76f95jjh89",
                "service": "",
                "port": {
                    "443": 18443,
                    "7070": 17070,
                    "7071": 17071,
                    "80": 18080,
                    "81": 18081,
                    "82": 18082,
                    "84": 18084,
                    "85": 18085,
                    "86": 18086,
                    "9090": 19090,
                    "9091": 16060,
                    "9092": 19091,
                    "9093": 16061,
                    "9443": 19443
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "enrolled-to-kmesh",
        "namespace": "echo-1-301",
        "hostname": "enrolled-to-kmesh.echo-1-301.svc.cluster.local",
        "vips": [
            "/10.96.104.169"
        ],
        "ports": {
            "443": 18443,
            "7070": 17070,
            "7071": 17071,
            "80": 18080,
            "81": 18081,
            "82": 18082,
            "84": 18084,
            "85": 18085,
            "86": 18086,
            "9090": 19090,
            "9091": 16060,
            "9092": 19091,
            "9093": 16061,
            "9443": 19443
        },
        "endpoints": {
            "Kubernetes//Pod/echo-1-301/enrolled-to-kmesh-v1-6bcff54977-hjf62": {
                "workloadUid": "Kubernetes//Pod/echo-1-301/enrolled-to-kmesh-v1-6bcff54977-hjf62",
                "service": "",
                "port": {
                    "443": 18443,
                    "7070": 17070,
                    "7071": 17071,
                    "80": 18080,
                    "81": 18081,
                    "82": 18082,
                    "84": 18084,
                    "85": 18085,
                    "86": 18086,
                    "9090": 19090,
                    "9091": 16060,
                    "9092": 19091,
                    "9093": 16061,
                    "9443": 19443
                }
            },
            "Kubernetes//Pod/echo-1-301/enrolled-to-kmesh-v2-6bf754956c-z44jx": {
                "workloadUid": "Kubernetes//Pod/echo-1-301/enrolled-to-kmesh-v2-6bf754956c-z44jx",
                "service": "",
                "port": {
                    "443": 18443,
                    "7070": 17070,
                    "7071": 17071,
                    "80": 18080,
                    "81": 18081,
                    "82": 18082,
                    "84": 18084,
                    "85": 18085,
                    "86": 18086,
                    "9090": 19090,
                    "9091": 16060,
                    "9092": 19091,
                    "9093": 16061,
                    "9443": 19443
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "service-with-waypoint-at-service-granularity",
        "namespace": "echo-1-301",
        "hostname": "service-with-waypoint-at-service-granularity.echo-1-301.svc.cluster.local",
        "vips": [
            "/10.96.159.27"
        ],
        "ports": {
            "443": 18443,
            "7070": 17070,
            "7071": 17071,
            "80": 18080,
            "81": 18081,
            "82": 18082,
            "84": 18084,
            "85": 18085,
            "86": 18086,
            "9090": 19090,
            "9091": 16060,
            "9092": 19091,
            "9093": 16061,
            "9443": 19443
        },
        "waypoint": {
            "destination": "echo-1-301/waypoint.echo-1-301.svc.cluster.local"
        },
        "endpoints": {
            "Kubernetes//Pod/echo-1-301/service-with-waypoint-at-service-granularity-v1-67c47775b5q44n6": {
                "workloadUid": "Kubernetes//Pod/echo-1-301/service-with-waypoint-at-service-granularity-v1-67c47775b5q44n6",
                "service": "",
                "port": {
                    "443": 18443,
                    "7070": 17070,
                    "7071": 17071,
                    "80": 18080,
                    "81": 18081,
                    "82": 18082,
                    "84": 18084,
                    "85": 18085,
                    "86": 18086,
                    "9090": 19090,
                    "9091": 16060,
                    "9092": 19091,
                    "9093": 16061,
                    "9443": 19443
                }
            },
            "Kubernetes//Pod/echo-1-301/service-with-waypoint-at-service-granularity-v2-5575b76f95ht5zk": {
                "workloadUid": "Kubernetes//Pod/echo-1-301/service-with-waypoint-at-service-granularity-v2-5575b76f95ht5zk",
                "service": "",
                "port": {
                    "443": 18443,
                    "7070": 17070,
                    "7071": 17071,
                    "80": 18080,
                    "81": 18081,
                    "82": 18082,
                    "84": 18084,
                    "85": 18085,
                    "86": 18086,
                    "9090": 19090,
                    "9091": 16060,
                    "9092": 19091,
                    "9093": 16061,
                    "9443": 19443
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "waypoint",
        "namespace": "echo-1-301",
        "hostname": "waypoint.echo-1-301.svc.cluster.local",
        "vips": [
            "/10.96.218.248"
        ],
        "ports": {
            "15008": 15008,
            "15021": 15021
        },
        "loadBalancer": {
            "mode": "Failover",
            "routingPreferences": [
                "Network",
                "Region",
                "Zone",
                "Subzone"
            ],
            "healthPolicy": "OnlyHealthy"
        },
        "endpoints": {
            "Kubernetes//Pod/echo-1-301/waypoint-6c8967c598-p6d62": {
                "workloadUid": "Kubernetes//Pod/echo-1-301/waypoint-6c8967c598-p6d62",
                "service": "",
                "port": {
                    "15008": 15008,
                    "15021": 15021
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "gateway-xu-istio",
        "namespace": "istio-system",
        "hostname": "gateway-xu-istio.istio-system.svc.cluster.local",
        "vips": [
            "/10.96.181.203"
        ],
        "ports": {
            "15021": 15021,
            "80": 80
        },
        "endpoints": {
            "Kubernetes//Pod/istio-system/gateway-xu-istio-687f5669df-9qpmq": {
                "workloadUid": "Kubernetes//Pod/istio-system/gateway-xu-istio-687f5669df-9qpmq",
                "service": "",
                "port": {
                    "15021": 15021,
                    "80": 80
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "istio-ingressgateway",
        "namespace": "istio-system",
        "hostname": "istio-ingressgateway.istio-system.svc.cluster.local",
        "vips": [
            "/10.96.165.40"
        ],
        "ports": {
            "15021": 15021,
            "443": 443,
            "80": 80
        },
        "endpoints": {
            "Kubernetes//Pod/istio-system/istio-ingressgateway-9cc99c9db-96tb8": {
                "workloadUid": "Kubernetes//Pod/istio-system/istio-ingressgateway-9cc99c9db-96tb8",
                "service": "",
                "port": {
                    "15021": 15021,
                    "443": 443,
                    "80": 80
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "istiod",
        "namespace": "istio-system",
        "hostname": "istiod.istio-system.svc.cluster.local",
        "vips": [
            "/10.96.16.3"
        ],
        "ports": {
            "15010": 15010,
            "15012": 15012,
            "15014": 15014,
            "443": 15017
        },
        "endpoints": {
            "Kubernetes//Pod/istio-system/istiod-597bc5d9fd-lmqxc": {
                "workloadUid": "Kubernetes//Pod/istio-system/istiod-597bc5d9fd-lmqxc",
                "service": "",
                "port": {
                    "15010": 15010,
                    "15012": 15012,
                    "15014": 15014,
                    "443": 15017
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "jaeger-collector",
        "namespace": "istio-system",
        "hostname": "jaeger-collector.istio-system.svc.cluster.local",
        "vips": [
            "/10.96.5.205"
        ],
        "ports": {
            "14250": 14250,
            "14268": 14268,
            "4317": 4317,
            "4318": 4318,
            "9411": 9411
        },
        "endpoints": {
            "Kubernetes//Pod/istio-system/jaeger-85b4ff864f-txqkn": {
                "workloadUid": "Kubernetes//Pod/istio-system/jaeger-85b4ff864f-txqkn",
                "service": "",
                "port": {
                    "14250": 14250,
                    "14268": 14268,
                    "4317": 4317,
                    "4318": 4318,
                    "9411": 9411
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "kiali",
        "namespace": "istio-system",
        "hostname": "kiali.istio-system.svc.cluster.local",
        "vips": [
            "/10.96.146.180"
        ],
        "ports": {
            "20001": 20001,
            "9090": 9090
        },
        "endpoints": {
            "Kubernetes//Pod/istio-system/kiali-6d7cb48555-2tbw2": {
                "workloadUid": "Kubernetes//Pod/istio-system/kiali-6d7cb48555-2tbw2",
                "service": "",
                "port": {
                    "20001": 20001,
                    "9090": 9090
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "prometheus",
        "namespace": "istio-system",
        "hostname": "prometheus.istio-system.svc.cluster.local",
        "vips": [
            "/10.96.182.235"
        ],
        "ports": {
            "9090": 9090
        },
        "endpoints": {
            "Kubernetes//Pod/istio-system/prometheus-bbcb484d4-fd55p": {
                "workloadUid": "Kubernetes//Pod/istio-system/prometheus-bbcb484d4-fd55p",
                "service": "",
                "port": {
                    "9090": 9090
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "tracing",
        "namespace": "istio-system",
        "hostname": "tracing.istio-system.svc.cluster.local",
        "vips": [
            "/10.96.246.6"
        ],
        "ports": {
            "16685": 16685,
            "80": 16686
        },
        "endpoints": {
            "Kubernetes//Pod/istio-system/jaeger-85b4ff864f-txqkn": {
                "workloadUid": "Kubernetes//Pod/istio-system/jaeger-85b4ff864f-txqkn",
                "service": "",
                "port": {
                    "16685": 16685,
                    "80": 16686
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "zipkin",
        "namespace": "istio-system",
        "hostname": "zipkin.istio-system.svc.cluster.local",
        "vips": [
            "/10.96.32.161"
        ],
        "ports": {
            "9411": 9411
        },
        "endpoints": {
            "Kubernetes//Pod/istio-system/jaeger-85b4ff864f-txqkn": {
                "workloadUid": "Kubernetes//Pod/istio-system/jaeger-85b4ff864f-txqkn",
                "service": "",
                "port": {
                    "9411": 9411
                }
            }
        },
        "ipFamilies": "IPv4"
    },
    {
        "name": "kube-dns",
        "namespace": "kube-system",
        "hostname": "kube-dns.kube-system.svc.cluster.local",
        "vips": [
            "/10.96.0.10"
        ],
        "ports": {
            "53": 53,
            "9153": 9153
        },
        "endpoints": {
            "Kubernetes//Pod/kube-system/coredns-76f75df574-49qc9": {
                "workloadUid": "Kubernetes//Pod/kube-system/coredns-76f75df574-49qc9",
                "service": "",
                "port": {
                    "53": 53,
                    "9153": 9153
                }
            },
            "Kubernetes//Pod/kube-system/coredns-76f75df574-8zls9": {
                "workloadUid": "Kubernetes//Pod/kube-system/coredns-76f75df574-8zls9",
                "service": "",
                "port": {
                    "53": 53,
                    "9153": 9153
                }
            }
        },
        "ipFamilies": "IPv4"
    }
]

```
