### ISSUE TITLE
TestServer_getAndSetBpfLevel failed 

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#905]
```
=== RUN   TestServer_getAndSetBpfLevel/workload
time="2024-09-27T01:22:16Z" level=info msg="kmesh start with Normal" subsys=bpf
coverage: 6.0% of statements
panic: test timed out after 10m0s
running tests:
	TestServer_getAndSetBpfLevel (10m0s)
	TestServer_getAndSetBpfLevel/workload (10m0s)

goroutine 35 [running]:
testing.(*M).startAlarm.func1()
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/src/testing/testing.go:2366 +0x265
created by time.goFunc
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/src/time/sleep.go:177 +0x45

goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc0000ef860, {0x408e9d7, 0x1c}, 0x41a56a8)
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/src/testing/testing.go:1750 +0x851
testing.runTests.func1(0xc0000ef860)
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/src/testing/testing.go:2161 +0x86
testing.tRunner(0xc0000ef860, 0xc000941b00)
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/src/testing/testing.go:1689 +0x21f
testing.runTests(0xc000454c78, {0x6107c00, 0x6, 0x6}, {0xc000941ba8?, 0xc000941bf0?, 0x63d3420?})
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/src/testing/testing.go:2159 +0x8bf
testing.(*M).Run(0xc0004b2aa0)
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/src/testing/testing.go:2027 +0xf18
main.main()
	_testmain.go:91 +0x2e5
```

**Comment by hzxuzhonghu** [comment]
cc @lec-bit
